<a href="https://colab.research.google.com/github/devsharmapolist/DATA-SCIENCE-COURSE-PW/blob/main/Practical_Questions_Numpy_Assignment_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

1. Create a 3x3 NumPy array with random integers between 1 and 100. Then, interchange its rows and columns.

In [1]:
import numpy as np

# Create a 3x3 NumPy array with random integers between 1 and 100
random_array = np.random.randint(1, 101, size=(3, 3))
print("Original Array:")
print(random_array)

# Interchange rows and columns (transpose the array)
transposed_array = random_array.T
print("\nTransposed Array:")
print(transposed_array)


Original Array:
[[96 64 82]
 [65 58 18]
 [77 78 84]]

Transposed Array:
[[96 65 77]
 [64 58 78]
 [82 18 84]]


2. Generate a 1D NumPy array with 10 elements. Reshape it into a 2x5 array, then into a 5x2 array.

In [4]:
import numpy as np

# Generate a 1D NumPy array with 10 elements
array_1d = np.arange(1, 11)  # Elements from 1 to 10
print("1D Array:")
print(array_1d)

# Reshape it into a 2x5 array
array_2x5 = array_1d.reshape(2, 5)
print("\nReshaped into 2x5 Array:")
print(array_2x5)

# Reshape it into a 5x2 array
array_5x2 = array_2x5.reshape(5, 2)
print("\nReshaped into 5x2 Array:")
print(array_5x2)



1D Array:
[ 1  2  3  4  5  6  7  8  9 10]

Reshaped into 2x5 Array:
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]

Reshaped into 5x2 Array:
[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]


3. Create a 4x4 NumPy array with random float values. Add a border of zeros around it, resulting in a 6x6 array.

In [5]:
import numpy as np

# Create a 4x4 NumPy array with random float values
array_4x4 = np.random.rand(4, 4)
print("Original 4x4 Array:")
print(array_4x4)

# Add a border of zeros around the array
array_with_border = np.pad(array_4x4, pad_width=1, mode='constant', constant_values=0)
print("\n6x6 Array with Border of Zeros:")
print(array_with_border)


Original 4x4 Array:
[[0.32031308 0.33466603 0.30911548 0.14677686]
 [0.87867223 0.58169031 0.53603142 0.62871799]
 [0.70440244 0.1820732  0.88705793 0.27487721]
 [0.01091025 0.26800707 0.00088954 0.5656599 ]]

6x6 Array with Border of Zeros:
[[0.         0.         0.         0.         0.         0.        ]
 [0.         0.32031308 0.33466603 0.30911548 0.14677686 0.        ]
 [0.         0.87867223 0.58169031 0.53603142 0.62871799 0.        ]
 [0.         0.70440244 0.1820732  0.88705793 0.27487721 0.        ]
 [0.         0.01091025 0.26800707 0.00088954 0.5656599  0.        ]
 [0.         0.         0.         0.         0.         0.        ]]


4. Using NumPy, create an array of integers from 10 to 60 with a step of 5

In [6]:
import numpy as np

# Create an array of integers from 10 to 60 with a step of 5
array = np.arange(10, 65, 5)
print("Array of integers from 10 to 60 with a step of 5:")
print(array)


Array of integers from 10 to 60 with a step of 5:
[10 15 20 25 30 35 40 45 50 55 60]


5. Create a NumPy array of strings ['python', 'numpy', 'pandas']. Apply different case transformations
(uppercase, lowercase, title case, etc.) to each element.

In [7]:
import numpy as np

# Create a NumPy array of strings
string_array = np.array(['python', 'numpy', 'pandas'])

# Apply uppercase transformation
uppercase_array = np.char.upper(string_array)
print("Uppercase Transformation:")
print(uppercase_array)

# Apply lowercase transformation
lowercase_array = np.char.lower(string_array)
print("\nLowercase Transformation:")
print(lowercase_array)

# Apply title case transformation
titlecase_array = np.char.title(string_array)
print("\nTitle Case Transformation:")
print(titlecase_array)

# Apply capitalize transformation (first character uppercase, rest lowercase)
capitalize_array = np.char.capitalize(string_array)
print("\nCapitalize Transformation:")
print(capitalize_array)


Uppercase Transformation:
['PYTHON' 'NUMPY' 'PANDAS']

Lowercase Transformation:
['python' 'numpy' 'pandas']

Title Case Transformation:
['Python' 'Numpy' 'Pandas']

Capitalize Transformation:
['Python' 'Numpy' 'Pandas']


6. Generate a NumPy array of words. Insert a space between each character of every word in the array.

In [8]:
import numpy as np

# Create a NumPy array of words
words_array = np.array(['python', 'numpy', 'pandas'])

# Insert a space between each character of every word
spaced_words_array = np.char.join(' ', words_array)
print("Array with spaces between characters:")
print(spaced_words_array)


Array with spaces between characters:
['p y t h o n' 'n u m p y' 'p a n d a s']


7. Create two 2D NumPy arrays and perform element-wise addition, subtraction, multiplication, and division.

In [9]:
import numpy as np

# Create two 2D NumPy arrays
array1 = np.array([[1, 2, 3], [4, 5, 6]])
array2 = np.array([[6, 5, 4], [3, 2, 1]])

# Perform element-wise addition
addition_result = array1 + array2
print("Element-wise Addition:")
print(addition_result)

# Perform element-wise subtraction
subtraction_result = array1 - array2
print("\nElement-wise Subtraction:")
print(subtraction_result)

# Perform element-wise multiplication
multiplication_result = array1 * array2
print("\nElement-wise Multiplication:")
print(multiplication_result)

# Perform element-wise division
division_result = array1 / array2
print("\nElement-wise Division:")
print(division_result)


Element-wise Addition:
[[7 7 7]
 [7 7 7]]

Element-wise Subtraction:
[[-5 -3 -1]
 [ 1  3  5]]

Element-wise Multiplication:
[[ 6 10 12]
 [12 10  6]]

Element-wise Division:
[[0.16666667 0.4        0.75      ]
 [1.33333333 2.5        6.        ]]


8. Use NumPy to create a 5x5 identity matrix, then extract its diagonal elements.

In [10]:
import numpy as np

# Create a 5x5 identity matrix
identity_matrix = np.eye(5)
print("5x5 Identity Matrix:")
print(identity_matrix)

# Extract the diagonal elements
diagonal_elements = np.diagonal(identity_matrix)
print("\nDiagonal Elements of the Identity Matrix:")
print(diagonal_elements)


5x5 Identity Matrix:
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]

Diagonal Elements of the Identity Matrix:
[1. 1. 1. 1. 1.]


9. Generate a NumPy array of 100 random integers between 0 and 1000. Find and display all prime numbers in
this array

In [11]:
import numpy as np

# Generate a NumPy array of 100 random integers between 0 and 1000
random_array = np.random.randint(0, 1001, size=100)
print("Random Array:")
print(random_array)

# Function to check if a number is prime
def is_prime(n):
    if n <= 1:
        return False
    for i in range(2, int(n**0.5) + 1):
        if n % i == 0:
            return False
    return True

# Find and display all prime numbers in the array
prime_numbers = [num for num in random_array if is_prime(num)]
print("\nPrime Numbers in the Array:")
print(prime_numbers)


Random Array:
[689 559 629 846 887 757 183 863 638 183 556  81 351 741 753 840 868   9
 690 600 130 586  44 889 812 394 334 141 975 279 926 982 128 296 886 399
  10  64 280 472 535 624 466   8  71 806 130 980 254 382 358  36 452 488
 294 810 373 515  92 953   8 520 581 833 501 966   4 655 889 385 956 604
 325 640 267 348 511 698 388 194   9 601 813 810 853 605 964 475 759 969
   9 199 762  94 360 288 983 374 453 768]

Prime Numbers in the Array:
[887, 757, 863, 71, 373, 953, 601, 853, 199, 983]


10. Create a NumPy array representing daily temperatures for a month. Calculate and display the weekly
averages.

In [14]:
import numpy as np

# Create a NumPy array representing daily temperatures for a month (30 days)
daily_temperatures = np.random.randint(15, 35, size=30)  # Temperatures between 15 and 35 degrees
print("Daily Temperatures for the Month:")
print(daily_temperatures)

# Reshape the array into 4 weeks (rows) and 7 days (columns)
weekly_temperatures = daily_temperatures.reshape(4, 7)

# Calculate and display the weekly averages
weekly_averages = weekly_temperatures.mean(axis=1)
print("\nWeekly Averages of Temperatures:")
print(weekly_averages)



Daily Temperatures for the Month:
[23 32 19 30 19 16 16 28 29 29 29 34 22 30 17 27 19 25 20 23 23 20 18 16
 34 21 28 34 32 27]


ValueError: cannot reshape array of size 30 into shape (4,7)